apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: doc-converter-worker
    app.kubernetes.io/part-of: api
  name: doc-converter-worker
  namespace: api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/enable-scale-to-zero: 'false'
        autoscaling.knative.dev/minScale: '1'
      labels:
        app: doc-converter-worker
        app.kubernetes.io/part-of: api
        networking.knative.dev/visibility: cluster-local
      namespace: api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: spot
                operator: In
                values:
                - 'true'
            weight: 1
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      containers:
      - name: doc-converter-worker
        image: presalytics/doc_converter_worker
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: REDIS_HOST
          value: lru-cache.redis.svc.cluster.local
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: LC_ALL
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8

  