apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-converter-worker
  namespace: api
  labels:
    app: doc-converter-worker
    app.kubernetes.io/part-of: api
spec:
  selector:
    matchLabels:
      app: doc-converter-worker 
  replicas: 1
  template:
    metadata:
      name: doc-converter
      namespace: api
      labels:
        app: doc-converter-worker
        app.kubernetes.io/part-of: api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: spot
                operator: In
                values:
                - 'true'
            weight: 1
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      containers:
      - name: doc-converter-worker
        image: presalytics/doc_converter_worker
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name: REDIS_HOST
          value: lru-cache.redis.svc.cluster.local
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: LC_ALL
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8
      